# Generated by Django 4.2.1 on 2023-08-18 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_project_current_folder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="current_folder",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.folder",
            ),
        ),
    ]
