# Generated by Django 4.2.1 on 2023-08-19 00:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_current_folder"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="folder",
            name="projects",
        ),
    ]
