# Generated by Django 4.2.1 on 2023-08-26 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_remove_folder_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                ("question_id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField(null=True)),
                ("answer", models.TextField(null=True)),
                ("created_on", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
