# Generated by Django 4.2.1 on 2023-08-26 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0005_question"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question",
            old_name="project_id",
            new_name="project",
        ),
    ]
