# Generated by Django 4.2.1 on 2023-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_name",
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name="project",
            name="video_link",
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
