# Generated by Django 4.2.1 on 2023-08-06 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="folders",
            field=models.ManyToManyField(blank=True, to="project.folder"),
        ),
        migrations.AddField(
            model_name="account",
            name="projects",
            field=models.ManyToManyField(blank=True, to="project.project"),
        ),
        migrations.AddField(
            model_name="account",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
