# Generated by Django 4.2.1 on 2023-06-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_project_created_on_project_project_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="video_link",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
