# Generated by Django 4.2.1 on 2023-06-11 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_project_project_name_alter_project_video_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="projects",
            field=models.ManyToManyField(null=True, to="core.project"),
        ),
    ]
