# Generated by Django 4.2.1 on 2023-06-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_account_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="projects",
            field=models.ManyToManyField(default=None, null=True, to="core.project"),
        ),
    ]
