# Generated by Django 4.2.1 on 2023-06-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_account_projects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="owner",
        ),
    ]
