# Generated by Django 4.2.1 on 2023-06-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_project_owner"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="projects",
            field=models.ManyToManyField(blank=True, to="project.project"),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
